### ISSUE TITLE
root_pandas fails to read in root file with index

### ISSUE THREAD

**Issue by MaxNoe** [ibab/root_pandas#5]
If I include the index into the root file with a script like this:

```{python}
import root_pandas as rpd
import numpy as np

data = rpd.DataFrame()
data["x"] = np.random.normal(0, 1, 1000)
data["y"] = np.random.normal(0, 1, 1000)

data.to_root("test.root", "test")

df = rpd.read_root("test.root", "test")
df.plot(x="x", y="y", kind="scatter")
```

It throws an error that it cannot convert from `long64`:

```
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    df = rpd.read_root("test.root", "test")
  File "/home/max_noethe/.local/lib/python2.7/site-packages/root_pandas/__init__.py", line 128, in read_root
    arr = root2array(path, tree_key, all_vars, selection=where, *kargs, **kwargs)
  File "/home/max_noethe/.local/lib/python2.7/site-packages/root_numpy/_tree.py", line 199, in root2array
    weight_name)
  File "tree.pyx", line 708, in _librootnumpy.root2array_fromFname (root_numpy/src/_librootnumpy.cpp:708)
  File "tree.pyx", line 623, in _librootnumpy.tree2array (root_numpy/src/_librootnumpy.cpp:623)
TypeError: cannot convert leaf index of branch index with type Long64_t (skipping)
```

**Comment by ibab** [comment]
Are you sure this is a problem with root_pandas and not root_numpy?
Also, are you sure you are using ROOT 5.34 and not 6?

**Comment by MaxNoe** [comment]
Ah, check. It works with root 5.34
